### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by musictopia2** [Anindra123/PasswordManagementApp#1]
I saw you have in windows forms.   Would you consider using blazor?  If so, then even as desktop app, you can use WPF with blazor webview control so the UI uses blazor which allows for more maintainable code.  If so, I can help with that part.

**Comment by Anindra123** [comment]
I am not that knowledgeable about blazor . I am thinking of upgrading the UI to WPF in the future and what you suggested might help greatly if it does allow more maintainable code . Will contact you for help then. Thanks for the suggestion

**Comment by musictopia2** [comment]
There is also a blazor webview control for windows forms as well.  Which means even if somebody decided to keep in windows forms, the entire ui otherwise is in blazor.  So a person just drops the UI control into the form, then all the work would be done in .razor files (which are blazor components).  I know a lot in blazor.  I had lots of experience with wpf/xaml.
However, I found its much easier to have maintainable code in blazor.  When you get to xaml, you have to do data binding with INotifyPropertyChanged and if there are exceptions on what to display, then converters has to be created so its a real mess.  When I found out about blazor and used it, then I found i was able to do much more maintainable code and have things more flexible.  Especially since its so easy to have blazor components.  Blazor allows you to do anything you want for the MVVM type of programming (has no opinions).

**Comment by Anindra123** [comment]
I will try to learn about blazor then when i will update the UI after completing necessary feature in this project. Will notify you then. Thanks for sharing this information.
