### ISSUE TITLE
Send User to Sign-In Page After Signing Up

### ISSUE THREAD

**Issue by westbrookmd** [Anindra123/PasswordManagementApp#2]
The current behavior for account creation alerts the user that the account was created and then clears out each input field.

I am proposing to either login the user with this information automatically or to send the user to the sign-in form.

I'd be happy to help - just let me know your thoughts on this!

**Comment by Anindra123** [comment]
I think sending the user to the sign in form would be great.
Feel free to add this change or let me know if you want me to add it.
