### ISSUE TITLE
Accounts Cannot Have the Same Password

### ISSUE THREAD

**Issue by westbrookmd** [Anindra123/PasswordManagementApp#5]
When attempting to try to create two accounts with different information but the same password, I receive this error:

"System.Data.SQLite.SQLiteException: 'constraint failed UNIQUE constraint failed: MasterAccTBL.master_password'"

How to Reproduce: Create two accounts with entirely different information but the same password.

**Comment by Anindra123** [comment]
Forgot about adding this check 🤦 . Thanks for reminding will add this check soon.

**Comment by Anindra123** [comment]
Bug fixed on commit "c02899e3cb7a3afa39fc455cc8e4d57df0daefb4"
